audio_normalization: false
audio_resize: false
audio_shape: &id001
- 2
- 257
- 166
batch_size: 32
beta1: 0.9
bv1_dataset_path: /home/public/BatvisionV1
bv2_dataset_path: /home/public/BatvisionV2
dataset: replica
decay_factor: 0.94
device: cuda
display_freq: 30000
epochs: 200
expr_dir: replica
input_size: 128
learning_rate_decrease_itr: 15
loss: silog_loss
lr: 0.0001
max_depth: 14.104
metadata_path: metadata/replica
model:
  audio_shape: *id001
  bins_channels: 256
  bins_drop: 0.5
  decoder_channels:
  - 1024
  - 512
  - 256
  - 256
  fusion_num_blocks: 1
  fusion_num_heads: 16
  fusion_type: DWAF
  input_size: 128
  max_depth: 14.104
  modal_fusion_att_drop: 0.5
  modal_fusion_ffn_drop: 0.5
  name: BaseLine_Audio_My_Fusion
  visual_encoder_type: tiny
modo: train
mp3d_dataset_path: /home/public/mp3d-dataset
num_workers: 8
optimizer: adam
replica_dataset_path: /home/public/replica-dataset
run_start_time: 24-07-19  19:07:15
validation_freq: 30000
variance_focus: 0.85
weight_decay: 0.0001
